[package]
name = "sysproxy"
version = "0.1.0"
edition = "2021"
authors = ["zzzgydi"]
license = "MIT"
readme = "README.md"
keywords = ["system proxy", "proxy"]

[dependencies]
thiserror = "1"

[target.'cfg(target_os = "macos")'.dependencies]
interfaces = "0.0.8"

[target.'cfg(target_os = "windows")'.dependencies]
winreg = {version = "0.10", features = ["transactions"]}
